<?php
require_once __DIR__ . '/config/bootstrap.php';
require_role('admin');

$db = getDB();

$filename = 'smart_stock_backup_' . date('Ymd_His') . '.sql';

header('Content-Type: application/sql; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Pragma: no-cache');
header('Expires: 0');

/* Order matters on restore: parents before children, because of the FKs. */
$tables = ['users', 'categories', 'suppliers', 'products', 'stock_in', 'stock_out',
           'activity_log', 'audit_log', 'notifications', 'settings'];

echo "-- =====================================================================\n";
echo "-- SMART STOCK -- database backup\n";
echo "-- Botol Anggun Sdn. Bhd.\n";
echo "-- Generated: " . date('d M Y, H:i:s') . "\n";
echo "-- Generated by: " . (current_user()['name'] ?? 'System') . "\n";
echo "--\n";
echo "-- Restore via SMART STOCK (Settings -> Backup & Restore) or phpMyAdmin.\n";
echo "-- =====================================================================\n\n";

echo "SET FOREIGN_KEY_CHECKS = 0;\n";
echo "SET NAMES utf8mb4;\n\n";

foreach ($tables as $table) {
    // Skip tables that don't exist (e.g. Demo 3 migration not yet run).
    try {
        $exists = $db->query("SHOW TABLES LIKE " . $db->quote($table))->fetch();
        if (!$exists) {
            continue;
        }
    } catch (Exception $e) {
        continue;
    }

    echo "-- ---------------------------------------------------------------------\n";
    echo "-- Table: $table\n";
    echo "-- ---------------------------------------------------------------------\n";

    $create = $db->query("SHOW CREATE TABLE `$table`")->fetch(PDO::FETCH_NUM);
    echo "DROP TABLE IF EXISTS `$table`;\n";
    echo $create[1] . ";\n\n";

    $rows = $db->query("SELECT * FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);
    if (empty($rows)) {
        echo "-- (no rows)\n\n";
        continue;
    }

    $columns = array_keys($rows[0]);
    $colList = '`' . implode('`, `', $columns) . '`';

    /* Batch inserts in chunks so very large tables stay readable and import fast. */
    $chunks = array_chunk($rows, 50);
    foreach ($chunks as $chunk) {
        echo "INSERT INTO `$table` ($colList) VALUES\n";
        $values = [];
        foreach ($chunk as $row) {
            $vals = [];
            foreach ($row as $v) {
                $vals[] = $v === null ? 'NULL' : $db->quote((string) $v);
            }
            $values[] = '  (' . implode(', ', $vals) . ')';
        }
        echo implode(",\n", $values) . ";\n";
    }
    echo "\n";
}

echo "SET FOREIGN_KEY_CHECKS = 1;\n\n";
echo "-- =====================================================================\n";
echo "-- End of backup\n";
echo "-- =====================================================================\n";

/* Log it after the dump is written so a logging failure can't corrupt the file. */
log_activity('Settings', 'Downloaded a database backup');
log_audit('Settings', 'BACKUP', 'Database', null);
notify('system', 'Database backup created', 'Backup file ' . $filename . ' was downloaded', 'settings.php');
